apiVersion: v1
kind: Service
metadata:
  name: rust-inference
  labels:
    app: rust-inference
spec:
  selector:
    app: rust-inference
  ports:
    - name: http
      port: 8081
      targetPort: http
  type: ClusterIP
